M:font_manager
F:G$engine_font_manager_char$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_char$ch$1$23({1}SC:U),B,1,4
S:Lfont_manager.engine_font_manager_char$x$1$23({1}SC:U),B,1,5
S:Lfont_manager.engine_font_manager_char$y$1$23({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_char$pnt$1$24({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_char$tile$1$24({1}SC:U),R,0,0,[c]
F:G$engine_font_manager_text$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_text$text$1$25({2}DG,SC:U),B,1,4
S:Lfont_manager.engine_font_manager_text$x$1$25({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_text$y$1$25({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_text$pnt$1$26({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_text$idx$1$26({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_text$tile$2$27({1}SC:S),R,0,0,[e]
F:G$engine_font_manager_data$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Lfont_manager.engine_font_manager_data$data$1$28({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_data$x$1$28({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_data$y$1$28({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_data$pnt$1$29({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_data$idx$1$29({1}SC:U),B,1,-2
S:Lfont_manager.engine_font_manager_data$tile$1$29({1}SC:S),R,0,0,[c]
S:Lfont_manager.engine_font_manager_data$quotient$1$29({2}SI:U),R,0,0,[e,d]
S:Lfont_manager.engine_font_manager_data$remainder$1$29({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_data$sloc0$1$0({1}SC:U),B,1,-1
F:G$engine_font_manager_data_ZERO$0$0({2}DF,SV:S),Z,0,3,0,0,0
S:Lfont_manager.engine_font_manager_data_ZERO$data$1$33({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_data_ZERO$x$1$33({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_data_ZERO$y$1$33({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_data_ZERO$pnt$1$34({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_data_ZERO$idx$1$34({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_data_ZERO$tile$1$34({1}SC:S),R,0,0,[e]
S:Lfont_manager.engine_font_manager_data_ZERO$hold$1$34({3}DA3d,SC:U),B,1,-5
S:Lfont_manager.engine_font_manager_data_ZERO$sloc0$1$0({2}DD,SC:U),B,1,-2
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
